### PR TITLE
meson: extract project version from header file and version .so

### PR DESCRIPTION
**Pull request by tp-m**
- Extract project version from `tinyalsa/version.h` for easier maintainability

- Version shared lib: tinyalsa.so -> tinyalsa.so.1.1.1

### CODE REVIEW

**Comment by tay10r** [comment]
I've seen other projects keep the version in a single text file. I think I'd like to do that instead of keeping it in the header.

**Comment by tp-m** [comment]
Never seen that, but in any case it's good practice to have the version also in the header file (at least in numerical form so it can be checked by `#if`). I just picked something that did the right thing without having to interfere with the other build systems.

**Comment by tay10r** [comment]
The version header will end up getting generated. I'll merge this anyway just meson has a version number until then. Thank you again for the contribution.

**Comment by tp-m** [comment]
Thanks! Sounds like a good plan, let me know if you need me to fix up anything for that.

**Comment by tay10r** [comment]
You can give it a shot if you like. I'm going to open some more issues for contributors to tackle if they chose to.

**Pull request merged**
