### PR TITLE
Easier Version Specification

### LINKED ISSUE #123: Easier Version Specification
Currently, the version is specified in:

 - `src/Makefile`
 - `debian/changelog`
 - `include/tinyalsa/version.h`

When a new release is made, the risk is present of one of these files not getting updated. There should be an easier way of ensuring that all the versions get updated correctly. Perhaps a script to search and replace the version numbers in the specified files.

For example a script, `scripts/bump-version.sh` or `scripts/bump-version.py` that can be used to specify the version in these files.

```
./scripts/bump-version.sh minor
# or ./scripts/bump-version.sh major
# or ./scripts/bump-version.sh patch
```

The header file can be used to parse the current version.

### PR DESCRIPTION
**Pull request by alexonea**
Fixes #123 

The following have changed, in chronological order:

1. e62ceb5
  - ```include/tinyalsa/version.h``` now generates the version string and the version binary representation based only on ```TINYALSA_VERSION_MAJOR```, ```TINYALSA_VERSION_MINOR``` and ```TINYALSA_VERSION_PATCH```. Therefore, the ```include/tinyalsa/version.h``` file is only (trusted) version specification file.
2. 3a6abfa
  - Introduced ```version-bump.sh```, currently only capable of reading the current version from ```include/tinyalsa/version.h```
  - Both ```meson``` and ```Makefile``` based builds now import the library version from the ```include/tinyalsa/version.h``` file through ```version-bump.sh```
  - ```cmake``` based build does not read the current version because it does not generate shared objects which need to be versioned using the library version numbers.
3. 891c04d
  - ```version-bump.sh``` now supports actual version bumping (i.e. releasing a new version). The new version can be released at major, minor or patch level and it is committed back to ```include/tinyalsa/version.h```
4. 52a7957
  - ```version-bump.sh``` now supports checks (i.e. it checks the version in ```include/tinyalsa/version.h``` against the latest released version in ```debian/changelog``` and reports mismatches.
  - checks have been activated for all three build systems as follows:
    - ```cmake``` and ```make``` perform the check during the build. ```cmake``` performs it right after building the library while ```cmake``` as the last build step.
    - ```meson``` performs the check before the build starts (at configure time) and does not allow the build to happen in case there is a version mismatch. Reason below.
  - ```meson``` build has to find the ```version-bump.sh``` script twice, I could't manage to make it look it up only once since it is required in the first statement which has to be ```program(...)```
5. 8652557..a6838a0
  - ```version-bump.sh``` has been renamed to ```version.sh``` for convenience.

A few remarks / questions:
1. The ```version.sh``` script is fairly complicated and I thought about using an already implemented and validated script such as [bumpversion](https://github.com/peritus/bumpversion). **Question is: do we care about an extra dependency?** If not, a 3rd party script doing basically the same thing would be a better choice. I implemented one here as well just to compare the effort.
2. Regarding the checks performed to make sure that ```debian/changelog``` stays in sync with the released versions: my opinion is that, since changing the version number is one of the last steps in the development / release cycle, it makes sense to halt a build in case they mismatch. The rationale is the following: once development is complete for a new release and we decide it is time to increment one of the version numbers, then, implicitly, it is also time to log what changed since the last release. If at this point we forget to update the changelog, new builds will fail until we do it. **Therefore: I would suggest that all build systems fail the build as soon as ```debian/changelog``` is out of sync as this clearly indicates that we skipped a step in the cycle (since we took the time to update the version => release ready code, but not the changelog).**

Usage of ```version.sh```:
```
$ ./scripts/version.sh 

Usage: ./scripts/version.sh [OPTIONS] ACTION

Available options:
  -s,--script   Format output in "script" mode (no trailing newline).
  -d,--dry-run  Does not commit anything to any file, just prints.

Available actions:
  print   [minor|major|patch]  Print the current version.
  release [minor|major|patch]  Bump the specified version part
  check                        Check the changelog latest released
                               version against the version file.

Please run this script from the project root folder.

```

### CODE REVIEW

**Comment by tay10r** [comment]
I disagree with the build system failing due to the change log being out of sync. This would affect anyone cloning the repository and they shouldn't be penalized for our forgetfulness. I agree with the strictness between the change log and the versioning so maybe it would be better for the CI to fail instead.

**Comment by tay10r** [comment]
@alexonea I'm going to merge this PR but I'd like to wait until we finish a discussion about syncing with Android's TinyALSA.

**Comment by alexonea** [comment]
I will then update the change so the check is added only to the CI scripts as a last step, also removing the check from all three build systems. Are you ok with this?

**Comment by tay10r** [comment]
@alexonea yes, that would be great!

**Comment by tay10r** [comment]
@alexonea I've merged your PR. Thanks for you help!

**Comment by alexonea** [comment]
@tay10r Thank you as well!

**Pull request merged**
