### PR TITLE
Added Example wav file

### PR DESCRIPTION
**Pull request by sjfricke**
still need to get added to sample

#100

### CODE REVIEW

**Comment by tay10r** [comment]
Can you convert this to a raw audio file?

Otherwise you're sending the WAV header to the audio device.

Make a note of what the channel count and the frame rate is before you convert it.

**Comment by tay10r** [comment]
Additionally, can you make sure it's a stereo channel configuration?

I think that most sound cards only support a stereo channel map.

**Comment by sjfricke** [comment]
I guess what I was thinking was an example of how to use tinyAlsa to take a wav, write it to a PCM buffer and play it back... I guess a spinoff of what tinyplay does but with the showcase of writing out the raw buffer as well

**Comment by tay10r** [comment]
Okay. I don't want to convolute that example too much, because it's meant to be short and to the point. I'd accept a PR for an additional example that demonstrates what you're describing. I won't be adding it myself anytime soon because I'm in the middle of extending the library and utilities.

**Comment by sjfricke** [comment]
No that is totally understandable, I was planning to make it short and not get caught up in error checking and what not since the file is there... ill write up the PR and we can go from there

**Comment by tay10r** [comment]
@sjfricke Thanks for bringing up this issue. It would be nice to have example files to play to ensure that the library is working on the target platform. I've created issue #113 detailing the requirements I ask of such examples.

I'm closing this due to inactivity and that the audio file attached is only part of what I would like to see in example audio files (see issue for details.)

Thank you again for bringing this up, it raised a good issue. If nobody gets to it, I'll get to it eventually.

**Comment by sjfricke** [comment]
Hey, sorry for inactivity, school has shifted focus away from the DSP projects I was working on. Thanks for follow up

**Comment by tay10r** [comment]
@sjfricke no worries, sure thing!

**Pull request closed without merging**
