### PR TITLE
Fix behaviors, remove 'prepared' and 'running' variables

### PR DESCRIPTION
**Pull request by pasqualirb**
Please review this in my fork. In pull requests GitHub reorder commits based on author date.

### CODE REVIEW

**Comment by pasqualirb** [comment]
> This is too large of a merge request. It would be easier for us both if you submitted these changes in smaller patches.

This is definitely an unusual pull request. It fixes many wrongly assumed behaviors. I'll improve and reorder some commits, and split changes into smaller pull requests.

> Overall, you seem to have made a lot of breaking changes and the behavior you changed is not documented.

The commit messages should explain what changes and why. The changes were based on ALSA (in kernel) and alsa-lib behaviors. Also, they should not break applications -- if they do, it's probably the application assuming something it should not.

> For example `pcm_readi` and `pcm_writei` no longer start the PCM if it hasn't already been started, yet the documentation says that it does still.

They do. See **The start behavior** section.

Here is some overview:

# The start behavior

In `pcm_writei()` it is assumed that when `pcm->running` is zero, start must be done and a write ioctl will do the start. Both are not true. See the third paragraph.

In `pcm_readi()` there is an assumption that the correct behavior is starting before calling read ioctl. This is not true. See the third paragraph.

Start is done **inside the write/read ioctl** (in kernel side) **when *start_threshold* or more frames are written/requested** (see [here](https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/tree/sound/core/pcm_lib.c?h=v4.20#n2246) for playback and [here](https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/tree/sound/core/pcm_lib.c?h=v4.20#n2179) for capture). Also, see the commit 7cdf4b9 "_pcm: Rewrite pcm_mmap_transfer() for compatibility_" which implements a similar behavior to read/write ioctl.

# The prepare behavior

The prepare action is currently done in `pcm_start()`. While preparing, application pointer is set to zero. If the user writes something (using mmaped buffer and control) before calling `pcm_start()`, after prepare it will be the same as nothing was written.

What makes it not prepare again every time is the `pcm->prepared` variable, which is discussed in the next section.

It seems better to prepare in `pcm_open()`, so the user doesn't even need to worry about preparing after setup. E.g. a write/read after `pcm_open()` without prepare would generally fail with EBADFD (see [here](https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/tree/sound/core/pcm_lib.c?h=v4.20#n2171)). It was not failing only because of the code removed in 791cc02  "*pcm: Remove code assuming start after write*" and 48c2ca0  "*pcm: Remove start before read*" commits, which was just commented in the previous section.

Given that application and hardware pointers become zero in prepare, they should be get from kernel. `pcm_sync_ptr()` should be called then (see the commit 5c6ecc5 "*pcm: Get appl_ptr and avail_min after prepare*").

Side note: Before 56d659f "*pcm: Create generic transfer*" commit, `pcm_readi()` does not prepare PCM when an overrun happens. Also, this commit allows read/write or mmap type of transfer according to `PCM_MMAP` flag; `tinyplay` fails when `--mmap` because `pcm_writei()` does not call `pcm_mmap_transfer()`.

# Remove prepared and running variables

`pcm->prepared` and `pcm->running` are a headache because **PCM state variable already exists** in status structure. They make the code behavior more difficult to predict as they act like a second unsynced source of an information that is already tricky to keep updated (e.g. Is status structure mmaped? When (after what) state can change?).

E.g.: In pcm_writei(), if ioctl returns an error, `prepared` and `running` are set to zero. However, the error might be EAGAIN, which means the write would block because the buffer is full -- and PCM is in running state (state was not changed).

# Rewrite `pcm_get_htimestamp()`

Commit: 0a1c540 "*pcm: Rewrite pcm_get_htimestamp()*".

The timestamp may be inconsistent with hardware pointer (used in available calculation). This happens when status is mmaped, hardware pointer is read, an interrupt occur, and timestamp is read.

# Rewrite `pcm_mmap_transfer()`

Although there is a commit rewriting this function (7cdf4b9 "*pcm: Rewrite pcm_mmap_transfer() for compatibility*"), it seems it has not any advantage over the read/write system calls. I've not removed it because there is an educational purpose in that. It shows -- in userspace -- more or less how read/write works.

--------------

Side note:

I have tried to arrange the order of the commits in a way that there was no breaking in functionality or behavior of the PCM interface between individual commits. At this point I noticed I did a mistake on that:

In the first commit (5541b0f "*pcm: Move prepare action to xrun handling*"), as prepare is not done in `pcm_open()` yet, a call to `pcm_writei()` would fail with EBADFD. I'll fix this. By the way, this is another confusion introduced by `prepared` and `running` variables.

**Comment by tay10r** [comment]
@pasqualirb Alright, give me some time to review the commits. I'll reopen this PR since you've made some more documentation on your changes, so you don't need to open another PR.

**Comment by pasqualirb** [comment]
This revision fixes some issues and changes the order of some commits. The code builds successfully after every commit.

Changes:

- Fix some comments that were not updated.
- Check for error after setting application pointer in `pcm_start()`.

In transfer:

- Return always `-1` when error.
- Recover from `SUSPENDED` state.

In the rewritten `pcm_mmap_transfer()`:

- Update `avail` variable after getting hardware pointer.
- Return the number of frames already written (if any) when playback start fails.

Take a look and tell about any issue. If no issues, I think it's good to merge.

**Comment by tay10r** [comment]
Merged. Thanks for the contributions. In the future just try to keep the PRs small.

**Pull request merged**
