### PR TITLE
pcm: Allow to wait if capture is not running

### PR DESCRIPTION
**Pull request by pasqualirb**
This allows starting capture from another thread.

See the commit 932a81519572 ("ALSA: pcm: Comment why read
blocks when PCM is not running") in Linux kernel.

### CODE REVIEW

**Comment by pasqualirb** [comment]
A [patch as an example](https://github.com/tinyalsa/tinyalsa/files/3112692/example.patch.txt) of a second thread starting capture.

**Comment by tay10r** [comment]
@pasqualirb do the tinycap and tinyplay programs still work? I'm not able to verify that this PR doesn't break any of the examples, although the code seems okay.

**Comment by pasqualirb** [comment]
> @pasqualirb do the tinycap and tinyplay programs still work? I'm not able to verify that this PR doesn't break any of the examples, although the code seems okay.

This must work because it is the same behavior done in [kernel read/write](https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/tree/sound/core/pcm_lib.c?h=sound-5.1-rc6#n2179). This affects the case of reading less than start_threshold frames in capture when state is PREPARED. Instead of returning 0 it will sleep because another thread may start pcm.

**Comment by pasqualirb** [comment]
@tay10r Have you been notified of my previous comment?

**Comment by tay10r** [comment]
@pasqualirb Thanks for the patch and sorry for the delay! Merged.

**Pull request merged**
