### PR TITLE
Plugin support

### PR DESCRIPTION
**Pull request by gajare-codeaurora**
These are initial set of patches to add the support for plugins to tinyalsa. Changes are to add PCM plugin support, perform several tasks for plugin (ex: hardware parameters validation, etc) such that plugin development is easier. Also add changes to support mixer control plugins. The mixer concept is split into groups, one for the hardware group and another for the virtual group.

Please review the Issue and the code changes and recommend any changes to either code/design, etc and I will work on absorbing them

This pull request corresponds to #135

### CODE REVIEW

**Comment by tay10r** [comment]
@gajare-codeaurora glad to see this! I'm traveling at the moment but will have a response at some point during this weekend. Thank you for getting this going!

**Comment by tay10r** [comment]
What is the origin of `libsndcardparser.so`? It seems, if I can make out the code correctly, that virtual PCMs cannot exist without the existence of this library.

**Comment by gajare-codeaurora** [comment]
@tay10r 
Thanks for the review. 
Yes, virtual PCMs cannot exist without the existence of libsndcardparser.so

Initially, had the implementation of libsndcardparser.so within tinyalsa, but there is a challenge with this. Eventually, we want to add plugins support for tinycompress as well (here https://github.com/alsa-project/tinycompress). The libsndcardparser.so is also needed by tinycompress to support virtual compress nodes. 
If libsndcardparser.so implementation is included within tinyalsa, then tinycompress has a dependency on tinyalsa. 

- Another option is to have libsndcardparser hosted as its own independent project which tinyalsa will depend on OR 
- Implement compress support within tinyalsa so compress and libsndcardparser.so can all reside within tinyalsa.

Could you please recommend which approach is better ?
I could temporarily upload a commit here with libsndcardparser.so on another pull request just for reviewing purpose if needed.

**Comment by tay10r** [comment]
My only Issue is that I would like to be able to load PCM and mixer plugins without the `libsndcardparser.so`. For example, having functions like:

```c
struct pcm* pcm_open_plugin(const char* plugin_path, unsigned int flags, const struct pcm_config* config);

struct mixer* mixer_open_plugin(const char* plugin_path);
```

This does away with  the need to call `libsndcardparser.so` from TinyALSA and TinyCompress.

I believe the reason you're opening `libsndcardparser.so` from `pcm_open` is so that there's almost no changes required of code that uses TinyALSA (or TinyCompress.) The only change that the code that uses these libraries would be the linking of `dl`. While this is highly convenient, I'm not so sure that functionality belongs there.

Have you considered the approach of opening mixers and PCMs from a different library? Perhaps having a single library in which the functionality of `libsndcardparser.so` resides. We'll call this hypothetical library, `libsndconfig`. A caller could expect to find these functions in it:

```c

/** Contains information regarding
 * a syntax error in a config file.
 */
struct sndconfig_err {
  /** The number of the line, starting at one, that the error was found at. */
  unsigned int line;
  /** The number of the column, starting at one, that the error was found at. */
  unsigned int column;
  /** A human-readable message describing the error that occurred. */
  const char* message;
};

/** A type definition for a function that handles
 * syntax errors found in a config file.
 */
typedef void (*sndconfig_errhandler)(void* e_data, const struct sndconfig_err* err);

/** Opens a sound configuration file.
 * @param config_path The path of the config file to open.
 * @param e_data An optional pointer to data that can be passed
 * to the error handler. May be NULL.
 * @param e_callback An optional pointer to a function
 * that handles syntax errors from the configuration file. May be NULL.
 * @returns On success, a sound configuration.
 * On failure, a null pointer.
 */
struct sndconfig* sndconfig_open(const char* config_path, void* e_data, sndconfig_errhandler e_callback);

/** Releases memory from a config.
 * @param config A pointer returned from @ref sndconfig_open
 */
void sndconfig_close(struct sndconfig* config);

/** Opens a PCM. The PCM may either be a plugin
 * or a hardware PCM, depending on the config file.
 * @returns A pointer to the PCM on success, a null pointer on failure.
 */
struct pcm* sndconfig_open_pcm(const struct sndconfig* config, unsigned int card, unsigned int device);

/** Opens a mixer. The mixer may either be a plugin
 * or a hardware mixer, depending on the config file.
 * @returns A pointer to a mixer on success, a null pointer on failure.
 */
struct mixer* sndconfig_open_mixer(const struct sndconfig* config, unsigned int card);
```

The call to `sndconfig_open` would do what `libsndcardparser.so` does, except that it would not require loading a dynamic library. There might already a library within the Android audio stack that does something like this, in which case a patch might be considered there instead of inventing a whole new library.

**Comment by gajare-codeaurora** [comment]
@tay10r 
>>Have you considered the approach of opening mixers and PCMs from a different library? Perhaps having a single library in which the functionality of libsndcardparser.so resides

one of the early designs was to encapsulate the libsndcardparser.so within tinyalsa (the APIs were actually quite similar to what you suggested) and build the whole package as libtinyalsa.so. But, with this we would have to re-implement or duplicate the libsndcardparser code into TinyCompress as well.

Not sure what you mean by having a single library to load PCMs, Mixers and perform virtual sound card parsing and who is the expected caller in this case ?
1. Do you mean this library will be something that tinyalsa and tinycompress will call into? In this case, not sure where this new library code should reside.
2. Or do you mean that user code (ex: application) will directly call into libsndconfig and libsndconfig internally calls either tinyalsa or tinycompress either with existing APIs like pcm_open or with newly added APIs like pcm_open_plugin based on either HW path or plugin path respectively 

We were trying to stick to the below requirements for this proposal
1. Callers of tinyalsa/tinycompress to continue using the same existing APIs and only the card numbers and/or device numbers will be different for plugins.
2. Support adding virtual PCMs and virtual Mixers to existing physical card (card registered from kernel)
3. Support for adding completely virtual cards 
4. Have no impact to current tinyalsa users/callers 

Could you please give a more details how you see the different library option to cater the requirements and be able to re-use the sound card parsing logic between tinyalsa and tinycompress.

**Comment by tay10r** [comment]
> @tay10r
> 
> > > Have you considered the approach of opening mixers and PCMs from a different library? Perhaps having a single library in which the functionality of libsndcardparser.so resides
> 
> one of the early designs was to encapsulate the libsndcardparser.so within tinyalsa (the APIs were actually quite similar to what you suggested) and build the whole package as libtinyalsa.so. But, with this we would have to re-implement or duplicate the libsndcardparser code into TinyCompress as well.
> 
> Not sure what you mean by having a single library to load PCMs, Mixers and perform virtual sound card parsing and who is the expected caller in this case ?
> 
>     1. Do you mean this library will be something that tinyalsa and tinycompress will call into? In this case, not sure where this new library code should reside.
> 
>     2. Or do you mean that user code (ex: application) will directly call into libsndconfig and libsndconfig internally calls either tinyalsa or tinycompress either with existing APIs like pcm_open or with newly added APIs like pcm_open_plugin based on either HW path or plugin path respectively

I mean 2

> We were trying to stick to the below requirements for this proposal
> 
>     1. Callers of tinyalsa/tinycompress to continue using the same existing APIs and only the card numbers and/or device numbers will be different for plugins.
> 
>     2. Support adding virtual PCMs and virtual Mixers to existing physical card (card registered from kernel)
> 
>     3. Support for adding completely virtual cards
> 
>     4. Have no impact to current tinyalsa users/callers
> 
> 
> Could you please give a more details how you see the different library option to cater the requirements and be able to re-use the sound card parsing logic between tinyalsa and tinycompress.

The way I understand number 4 specifically is: do not break compilation of projects currently using TinyALSA.

There seems to be an implicit 5th requirement: to add virtual cards and devices to existing code without the existing code having to change.

Do I understand this correctly?

**Comment by gajare-codeaurora** [comment]
>>The way I understand number 4 specifically is: do not break compilation of projects currently using TinyALSA.

Yes this is correct.

>>There seems to be an implicit 5th requirement: to add virtual cards and devices to existing code without the existing code having to change.
Do I understand this correctly?

Yes, there are many frameworks/HALs/test-suites for android/non-android/IOT etc that are currently using tinyalsa APIs, the intention is to absorb all the plugin related changes inside of tinyalsa and oblivious to that of the callers. We feel that changing tinyalsa APIs to callers has a bigger impact to the overall audio ecosystem across platforms, OS'es, frameworks, vendor specific applications etc and would like to avoid that as much as possible.

**Comment by tay10r** [comment]
@gajare-codeaurora I'm sorry but I feel very strongly that a call to `dlopen` should not be snuck into `pcm_open`. At the very least, it should be in a separate function. While it doesn't have any compile time impact on the library, it does introduce a lot more possible failure points to the library. For example, what if `sndcardparser.so` aborts? What about syntax errors in the config file? Why are we assuming that the projects that use this library will consider plugin support to be worth the risk?

**Comment by gajare-codeaurora** [comment]
Hi @tay10r, Thanks for your response. Sorry, i was on leave for a few days and could not follow up on this. 

I fully agree with your comment that call to dlopen(sndcardparser) within pcm_open makes the library prone to more failure points. 
But, in case of users using this library and not wanting to use plugins will not have the libsandcardparser.so installed at all and the dlopen just fails causing the pcm_open to just open the hardware pcm node, so i dont think there is any risk to users due to this code if they do not want to use plugin support. 

Thinking about this more, i think there is very little to no gain of allowing the hardware nodes description to be part of the pcm configs. In that case, we can keep the pcm_configs to describe only the virtual nodes. If that is the case, we can make our code more robust by using this sequence as below:

pcm_open
   always try to open /dev/snd/pcm*
   IF /dev/snd/pcm* open succeeds: 
   THEN
          return to caller, setup hw path for this pcm.
    ELSE (/dev/snd/pcm* open returns ENODEV)
          try dlopen sndcardparser
          check if virtual node exists 
          open virtual node if present (if not present, return error to caller)
        
I think this may help make the library robust for hardware node usage and projects that do not use plugins. Please let me know your views on this. 

Of course, the concept of dlopen altogether can be revisited. Will wait for your comments before heading the discussion on that road.

**Comment by tay10r** [comment]
@gajare-codeaurora I like the idea of opening PCM nodes first. I still insist that the plugins are not attempted to be opened in the existing `pcm_open` function.

Simon and I had discussed this PR over email, and here's what we agree on.

 - The PR is quite large. I'm personally not sure if you could've made it smaller, since most of it's new code. On the chance that you submit a new PR, try to make it a bit smaller if you can. If not, we'll just deal with it as is.
 - The call to open plugins should be separately from `pcm_open`.
 - The function `put_card` has a name that's kind of confusing. Wouldn't it be better named something like `close_card`?

Regarding `plug_ops` and `hw_ops`, I would like these symbols to be declared `extern` in `pcm_io.h` so that there's some type safety in the symbol lookup. I would also like if these structures were declared `const`.

**Comment by tay10r** [comment]
@pasqualirb Thanks for the input! Bhalchandra and I had discussed over email that TinyALSA would inherit some plugin functionality. We both seem to agree that the `pcm` and `mixer` structures should have a point of indirection so that they may either be a hardware device or virtual one. Now we're just concerned with out to achieve that.

**Comment by gajare-codeaurora** [comment]
>>I like the idea of opening PCM nodes first. I still insist that the plugins are not attempted to be opened in the existing pcm_open function.

@tay10r  would it make more sense to refactor the code under compile time flag (say for example TINYALSA_USES_PLUGINS). If this is set to false in the makefile then the pcm_open implementation stays the same as it is (no code for plugins). And if set to true the pcm_open will redirect to another static function say __pcm_open(..) that would encapsulate the hw_open as well as the plugin_open functionality. 

I think this should completely remove any risks of the new changes impacting the existing tinyalsa users. It is of course unavoidable to have risks if users enable the TINYALSA_USES_PLUGINS flag and intend to implement their own plugin. 

>>The function put_card has a name that's kind of confusing. Wouldn't it be better named something like close_card?
Sure, will change the name to indicate like open_card and close_card 

>>Regarding plug_ops and hw_ops, I would like these symbols to be declared extern in pcm_io.h so that there's some type safety in the symbol lookup. I would also like if these structures were declared const
Sure, will make this changes and upload new patchset.

**Comment by tay10r** [comment]
@gajare-codeaurora I think that would work if the flag was disabled by default. I would like to put off enabling this by default until the next major revision.

**Comment by gajare-codeaurora** [comment]
Thanks @tay10r 
Will make the changes and update the PR. Also working on to check if i can reduce the code size somehow. Hoping to have the new changes out by end of the week 10/25

**Comment by gajare-codeaurora** [comment]
@tay10r 
Please review the latest patchset for the pcm plugins support. I have incorporated the minor changes for function name changes and marking the ops structures as extern.

Also, below updates for PCM
   - Did minimal changes to make sure the plugin open is only done if compile flag TINYALSA_USES_PLUGINS is set 
   - HW nodes are given first priority and the new code tries always to open HW node first, attempts to open plugin only when HW node open fails. 
   - Currently still retained the interface routing logic (with function pointers) even if the compile time flag is not set. If we want the whole pcm_open code untouched when compile time flag = false, this will cause code duplication for pcm_open, and i think code duplication is very hard to maintain in a long run. 

Also, as of now, the mixer plugins part is untouched. Mixer plugins are a bit complicated since mixer_open can have both HW mixer ctls and virtual mixer controls co-exist. Please let me know your views on the current PCM changes. I think we need to incorporate TINYALSA_USES_PLUGINS for mixer code as well, but will hold off making those changes until we figure out the PCM code first.

**Comment by tay10r** [comment]
@gajare-codeaurora Thanks for your ongoing patience in handling the changes so far.

I ran a test with valgrind of the program `tinycap` and found that this patch introduces a memory leak.

```
==20800== Memcheck, a memory error detector
==20800== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20800== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==20800== Command: ./tinycap test.wav
==20800== 
==20800== 
==20800== HEAP SUMMARY:
==20800==     in use at exit: 24 bytes in 1 blocks
==20800==   total heap usage: 6 allocs, 5 frees, 25,352 bytes allocated
==20800== 
==20800== 24 bytes in 1 blocks are definitely lost in loss record 1 of 1
==20800==    at 0x483CB35: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==20800==    by 0x10D710: pcm_hw_open (pcm_hw.c:87)
==20800==    by 0x10C45C: pcm_open (pcm.c:892)
==20800==    by 0x10AB65: capture_sample (tinycap.c:230)
==20800==    by 0x10AA35: main (tinycap.c:187)
==20800== 
==20800== LEAK SUMMARY:
==20800==    definitely lost: 24 bytes in 1 blocks
==20800==    indirectly lost: 0 bytes in 0 blocks
==20800==      possibly lost: 0 bytes in 0 blocks
==20800==    still reachable: 0 bytes in 0 blocks
==20800==         suppressed: 0 bytes in 0 blocks
==20800== 
==20800== For counts of detected and suppressed errors, rerun with: -v
==20800== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

I also notice that some of the functions that release resources back to the system still use the `put` convention. Any function that releases resources back to the system needs a better name than that. Maybe that convention exists in some projects, but I'd rather not have it.

Please use `*close*`, `*free*` or anything similar to `*destroy*` or `*release*`.

Again, thanks all the code so far and I am pretty excited to get this into upstream.

**Comment by rohkkumar** [comment]
@tay10r  Thank you for reviewing the code. @gajare-codeaurora  is on vacation. I will update the patches in his absence.
Regarding memory leak, I will found the issue. Also, regarding put convention, I have decided to use open/close instead of get/put for snd_utils_get/put_dev_node( ). I hope that works. 

I will try to upload the fix in a day or two. Can you please let us know if there is any other comment/query on current patchset so that I can accommodate other change, if any.

**Comment by tay10r** [comment]
@rohkkumar Thanks for the update! Yes, I would be alright with open/close. I'll try to put some more time into the review so we can get this merged sooner rather than later.

**Comment by tay10r** [comment]
@gajare-codeaurora perhaps I can make the changes I'd like to see and I'll send you a PR that you can review. Would that work for you? I don't think it'll be anything more than superficial changes.

**Comment by gajare-codeaurora** [comment]
@tay10r , I was waiting for your code review comments to make the changes. You can either comment on the code or as you mentioned make the changes and create a PR, i am okay either way, whichever is more convenient for you is fine with me.

**Comment by tay10r** [comment]
@gajare-codeaurora I would like to make the changes and submit a PR if it makes no difference. I should be able to get to it by Friday.

**Comment by tay10r** [comment]
I've sent you a PR of some minor changes. The next set of changes I'm going to propose have to do with the `snd_node` structure. Here's a list of issues that I will be addressing:

 - This structure defines the function prototypes used in the actual plugin library, but it is not a public header. This makes it difficult for a plugin to be developed because it wouldn't be available with the API headers.
 - This structure appears to only work with one card and one device at a time. I think it would be better for the plugin to act as a virtual sound card, from which a mixer and multiple PCMs can be opened from.
 - The "device" constructor is homogeneous when it should be heterogeneous, especially if the plugin architecture should support tinycompress type plugin. For example:

```c
void* (*get_node)(void* card, int id, int type);
```

Should really just be:

```c
void* (*open_pcm)(void* card, int device);
void* (*open_mixer)(void* card);
```

Or even better:

```c
struct pcm* (*open_pcm)(void* card, int device, int flags);
struct mixer* (*open_mixer)(void* card);
```

Which would require new constructors for `pcm` and `mixer` that would
probably look something like this:

```c
struct pcm* open_pcm_plugin(const struct pcm_plugin_ops* ops, struct pcm_plugin* plugin_data);
struct mixer* open_mixer_plugin(const struct mixer_plugin_ops* ops, struct mixer_plugin* plugin_data);
```

These are issues I will be addressing in the next PR.

**Comment by gajare-codeaurora** [comment]
@tay10r 
Thanks for the changes, all of the changes look good to me. Will wait for your next PR with further changes.

**Comment by rohkkumar** [comment]
Hello @tay10r , I have updated this PR with all changes included and fixed some clang issues too.

**Comment by tay10r** [comment]
@rohkkumar sorry I didn't see this! My issue board recently got spammed and sort of hid all the other issues.

I just want to be sure of this system before I merge, since there really can't be any take backs. I'd like to consider one more option.

What if we opened a PCM or mixer plugin by checking for a ".so" extension in `pcm_open` and `mixer_open`? I think that would remove the need of having the `snd_node` related structures and I would be much happier with the design. The only end difference the user would see is specifying a ".so" file instead of a `/dev/snd/` file.

**Comment by rohkkumar** [comment]
Thank you @tay10r . We can definitely work to make plugin more useful to others too and make it perfect. The major drive towards this design was to not impact any existing API definition as it will impact the complete ecosystem using tinyalsa. 
I will send mail to you for tinycompress upstream before sending PR.

**Pull request merged**
